[package]
name = "bottle"
version = "0.2.0-prealpha"
authors = ["Kevin Stenerson"]
repository = "https://github.com/gobottle/bottle"
license = "BSD-3-Clause"
publish = true

root = "src"

[[bin]]
name = "bottle"
path = "main.go"
